// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQFMJb9iEp1ocnyKOoBaYhIYLloF3-qWU',
    appId: '1:263469891035:web:5d5765225600a3c83b7bfe',
    messagingSenderId: '263469891035',
    projectId: 'quiniela-mundial-2026-3e2b7',
    authDomain: 'quiniela-mundial-2026-3e2b7.firebaseapp.com',
    storageBucket: 'quiniela-mundial-2026-3e2b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPsiz_QPaKqj0LRzOeXvVESCpNn8EukyM',
    appId: '1:263469891035:android:6ec8205e7bb2aa873b7bfe',
    messagingSenderId: '263469891035',
    projectId: 'quiniela-mundial-2026-3e2b7',
    storageBucket: 'quiniela-mundial-2026-3e2b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz4MFhf5fH0VjYnDREi4ceM7dzercUN1k',
    appId: '1:263469891035:ios:e485414d020e0e8c3b7bfe',
    messagingSenderId: '263469891035',
    projectId: 'quiniela-mundial-2026-3e2b7',
    storageBucket: 'quiniela-mundial-2026-3e2b7.firebasestorage.app',
    iosClientId: '263469891035-2m3j5hbo8pitfqc5q2lt14mlqbgfccit.apps.googleusercontent.com',
    iosBundleId: 'com.example.quiniela2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz4MFhf5fH0VjYnDREi4ceM7dzercUN1k',
    appId: '1:263469891035:ios:e485414d020e0e8c3b7bfe',
    messagingSenderId: '263469891035',
    projectId: 'quiniela-mundial-2026-3e2b7',
    storageBucket: 'quiniela-mundial-2026-3e2b7.firebasestorage.app',
    iosClientId: '263469891035-2m3j5hbo8pitfqc5q2lt14mlqbgfccit.apps.googleusercontent.com',
    iosBundleId: 'com.example.quiniela2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQFMJb9iEp1ocnyKOoBaYhIYLloF3-qWU',
    appId: '1:263469891035:web:a0816859ddbe16ae3b7bfe',
    messagingSenderId: '263469891035',
    projectId: 'quiniela-mundial-2026-3e2b7',
    authDomain: 'quiniela-mundial-2026-3e2b7.firebaseapp.com',
    storageBucket: 'quiniela-mundial-2026-3e2b7.firebasestorage.app',
  );
}
